# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.187.0/containers/typescript-node/.devcontainer/base.Dockerfile

# [Choice] Node.js version: 14, 12, 10
ARG VARIANT="14-buster"
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:0-${VARIANT}

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment if you want to tweak where npm global packages are installed. See https://aka.ms/vscode-remote/containers/non-root-user for details.
# ENV NPM_GLOBAL /usr/local/share/npm-global
# ENV PATH ${PATH}:${NPM_GLOBAL}/bin
# RUN sudo chown -R node ${NPM_GLOBAL}
